name: phoenix

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.4.0+14

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # UI Related
  another_flushbar: ^1.12.30
  another_xlider: ^1.1.2
  animated_text_kit: ^4.2.2
  page_transition: ^2.2.1
  palette_generator: ^0.3.3+5
  sleek_circular_slider: ^2.1.0
  sliding_up_panel: ^2.0.0+1


  # AUDIO Related
  audio_service: ^0.18.17
  ffmpeg_kit_flutter_new: ^4.4.2
  just_audio: ^0.10.4
  on_audio_edit: ^1.4.0+1
  on_audio_query: ^2.9.0


  # FLUTTER Related
  device_info_plus: ^11.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  provider: ^6.1.4
  share_plus: ^10.1.4
  flutter_displaymode: ^0.6.0


  # DATABASE Related
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  # ICONS Related
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_remixicon:
    git: https://github.com/KarimAbdo/flutter_remixicon.git
  ionicons_plus: ^0.2.5
  flutter_material_design_icons: ^3.1.0+7447


  # WEB Related
  http: ^1.4.0
  html: ^0.15.5
  html_unescape: ^2.0.0
  url_launcher: ^6.3.1


  # MISCELLANEOUS
  awesome_notifications: ^0.10.1
  screenshot: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.35


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  uses-material-design: true

  assets:
    - assets/res/

  fonts:
    - family: NightMachine
      fonts:
        - asset: assets/fonts/NightMachine-Regular.otf

    - family: Urban
      fonts:
        - asset: assets/fonts/Urbanist-Regular.otf
        - asset: assets/fonts/Urbanist-Light.otf
          weight: 300
        - asset: assets/fonts/Urbanist-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.otf
        - asset: assets/fonts/Raleway-Thin.otf
          weight: 100
        - asset: assets/fonts/Raleway-SemiBold.otf
          weight: 600

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf

    - family: Futura
      fonts:
        - asset: assets/fonts/FuturaLT.ttf

    - family: Graviticons
      fonts:
        - asset: assets/fonts/Graviticons.ttf
